### ISSUE TITLE
Some github urls aren't installable

### ISSUE THREAD

**Issue by jonathanpenn** [densitypop/Vimmer#7]
I'm unable to install the ctags plugin with this command:

```
 vimmer install https://github.com/vim-scripts/ctags.vim
```

It responds with

```
The URL https://github.com/vim-scripts/ctags.vim is invalid.
```

**Comment by joefiorini** [comment]
This is a problem with the regex I'm using to validate Github URLs. Will fix and push soon!

**Comment by joefiorini** [comment]
Pushed the fix to the develop branch. I'm going to close. Let me know if you have further problems. Thanks!
